# Generated by Django 5.2.11 on 2026-02-25 20:52

import accounts.models
import django.db.models.deletion
import django.utils.timezone
import django_countries.fields
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name='phone number')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='date of birth')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures/')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='address')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='city')),
                ('state', models.CharField(blank=True, max_length=100, verbose_name='state/province')),
                ('postal_code', models.CharField(blank=True, max_length=20, verbose_name='postal code')),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2, verbose_name='country')),
                ('preferred_language', models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('fr', 'French'), ('de', 'German')], default='en', max_length=10, verbose_name='preferred language')),
                ('preferred_currency', models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound')], default='USD', max_length=3, verbose_name='preferred currency')),
                ('is_email_verified', models.BooleanField(default=False, verbose_name='email verified')),
                ('is_phone_verified', models.BooleanField(default=False, verbose_name='phone verified')),
                ('marketing_opt_in', models.BooleanField(default=True, verbose_name='marketing opt-in')),
                ('is_business_account', models.BooleanField(default=False, verbose_name='business account')),
                ('email_verified_at', models.DateTimeField(blank=True, null=True, verbose_name='email verified at')),
                ('phone_verified_at', models.DateTimeField(blank=True, null=True, verbose_name='phone verified at')),
                ('last_activity', models.DateTimeField(auto_now=True, verbose_name='last activity')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            managers=[
                ('objects', accounts.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='BusinessAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255, verbose_name='company name')),
                ('company_registration_number', models.CharField(blank=True, max_length=100, verbose_name='registration number')),
                ('company_vat_number', models.CharField(blank=True, max_length=100, verbose_name='VAT number')),
                ('company_size', models.CharField(choices=[('1-10', '1-10 employees'), ('11-50', '11-50 employees'), ('51-200', '51-200 employees'), ('201-500', '201-500 employees'), ('501-1000', '501-1000 employees'), ('1000+', '1000+ employees')], max_length=50, verbose_name='company size')),
                ('industry', models.CharField(blank=True, max_length=100, verbose_name='industry')),
                ('company_address', models.TextField(blank=True, verbose_name='company address')),
                ('company_phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name='company phone')),
                ('company_email', models.EmailField(blank=True, max_length=254, verbose_name='company email')),
                ('billing_address', models.TextField(blank=True, verbose_name='billing address')),
                ('payment_terms', models.CharField(choices=[('prepaid', 'Prepaid'), ('net15', 'Net 15'), ('net30', 'Net 30'), ('net60', 'Net 60')], default='net30', max_length=50, verbose_name='payment terms')),
                ('approval_required', models.BooleanField(default=False, help_text='Whether bookings require approval', verbose_name='approval required')),
                ('spending_limit', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='monthly spending limit')),
                ('travel_policy', models.TextField(blank=True, verbose_name='travel policy')),
                ('is_verified', models.BooleanField(default=False, verbose_name='verified')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='verified at')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='business_account', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_business_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'business account',
                'verbose_name_plural': 'business accounts',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('travel_style', models.CharField(blank=True, choices=[('budget', 'Budget Traveler'), ('luxury', 'Luxury Traveler'), ('business', 'Business Traveler'), ('family', 'Family Traveler'), ('adventure', 'Adventure Seeker'), ('relaxation', 'Relaxation Seeker')], max_length=50, verbose_name='travel style')),
                ('accommodation_preferences', models.JSONField(blank=True, default=dict, help_text='Preferred accommodation types and amenities', verbose_name='accommodation preferences')),
                ('flight_preferences', models.JSONField(blank=True, default=dict, help_text='Preferred airlines, seat types, etc.', verbose_name='flight preferences')),
                ('frequent_flyer_numbers', models.JSONField(blank=True, default=dict, help_text='Airline loyalty program numbers', verbose_name='frequent flyer numbers')),
                ('passport_number', models.CharField(blank=True, max_length=50, verbose_name='passport number')),
                ('passport_expiry', models.DateField(blank=True, null=True, verbose_name='passport expiry date')),
                ('id_document', models.FileField(blank=True, null=True, upload_to='id_documents/', verbose_name='ID document')),
                ('emergency_contact_name', models.CharField(blank=True, max_length=100, verbose_name='emergency contact name')),
                ('emergency_contact_phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name='emergency contact phone')),
                ('emergency_contact_relationship', models.CharField(blank=True, max_length=50, verbose_name='relationship')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user profile',
                'verbose_name_plural': 'user profiles',
            },
        ),
    ]
