# Generated by Django 5.2.11 on 2026-02-28 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('host', 'Host'), ('car_owner', 'Car Owner'), ('admin', 'Admin')], default='customer', help_text='Determines platform permissions such as host or admin', max_length=20, verbose_name='role'),
        ),
    ]
