# Generated by Django 5.2.11 on 2026-02-28 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_alter_review_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='verified_booking',
            field=models.BooleanField(default=False, verbose_name='verified booking'),
        ),
    ]
