# Generated by Django 5.2.11 on 2026-02-27 12:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability',
            name='available_rooms',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(10000)], verbose_name='available rooms'),
        ),
        migrations.AlterField(
            model_name='availability',
            name='max_stay',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(365)], verbose_name='maximum stay'),
        ),
        migrations.AlterField(
            model_name='availability',
            name='min_stay',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(365)], verbose_name='minimum stay'),
        ),
        migrations.AlterField(
            model_name='availability',
            name='total_rooms',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(10000)], verbose_name='total rooms'),
        ),
        migrations.AlterField(
            model_name='priceplan',
            name='cancellation_days',
            field=models.PositiveSmallIntegerField(default=0, help_text='Days before check-in for free cancellation', validators=[django.core.validators.MaxValueValidator(365)], verbose_name='free cancellation days'),
        ),
        migrations.AlterField(
            model_name='priceplan',
            name='max_nights',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(365)], verbose_name='maximum nights'),
        ),
        migrations.AlterField(
            model_name='priceplan',
            name='min_nights',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(365)], verbose_name='minimum nights'),
        ),
        migrations.AlterField(
            model_name='property',
            name='booking_count',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(999999999)], verbose_name='booking count'),
        ),
        migrations.AlterField(
            model_name='property',
            name='review_count',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(999999999)], verbose_name='review count'),
        ),
        migrations.AlterField(
            model_name='property',
            name='star_rating',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1 Stars'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')], null=True, validators=[django.core.validators.MaxValueValidator(5)], verbose_name='star rating'),
        ),
        migrations.AlterField(
            model_name='property',
            name='total_rooms',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(10000)], verbose_name='total rooms'),
        ),
        migrations.AlterField(
            model_name='property',
            name='view_count',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(999999999)], verbose_name='view count'),
        ),
        migrations.AlterField(
            model_name='property',
            name='year_built',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1800), django.core.validators.MaxValueValidator(2100)], verbose_name='year built'),
        ),
        migrations.AlterField(
            model_name='property',
            name='year_renovated',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1800), django.core.validators.MaxValueValidator(2100)], verbose_name='year renovated'),
        ),
        migrations.AlterField(
            model_name='propertyimage',
            name='display_order',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(999)], verbose_name='display order'),
        ),
        migrations.AlterField(
            model_name='room',
            name='floor',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(200)], verbose_name='floor'),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='bathroom_count',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(10)], verbose_name='bathroom count'),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='bed_count',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(20)], verbose_name='bed count'),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='display_order',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(999)], verbose_name='display order'),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='max_adults',
            field=models.PositiveSmallIntegerField(default=2, validators=[django.core.validators.MaxValueValidator(50)], verbose_name='maximum adults'),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='max_children',
            field=models.PositiveSmallIntegerField(default=2, validators=[django.core.validators.MaxValueValidator(50)], verbose_name='maximum children'),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='max_occupancy',
            field=models.PositiveSmallIntegerField(default=4, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='maximum occupancy'),
        ),
    ]
