# Generated by Django 5.2.11 on 2026-02-28 10:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_alter_availability_available_rooms_and_more'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyAvailability',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='active')),
                ('date', models.DateField(db_index=True, verbose_name='date')),
                ('is_available', models.BooleanField(default=True, verbose_name='available')),
                ('price_override', models.DecimalField(blank=True, decimal_places=2, help_text='Optional price override for this date', max_digits=10, null=True, verbose_name='price override')),
            ],
            options={
                'verbose_name': 'property availability',
                'verbose_name_plural': 'property availability',
            },
        ),
        migrations.RemoveIndex(
            model_name='property',
            name='properties__country_f5203b_idx',
        ),
        migrations.RemoveField(
            model_name='property',
            name='host',
        ),
        migrations.AddField(
            model_name='property',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='approved at'),
        ),
        migrations.AddField(
            model_name='property',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_properties', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='property',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='deleted at'),
        ),
        migrations.AddField(
            model_name='property',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_soft_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='property',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='active'),
        ),
        migrations.AddField(
            model_name='property',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, verbose_name='deleted'),
        ),
        migrations.AddField(
            model_name='property',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='Listing owner/host', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='owned_properties', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='property',
            name='rejection_reason',
            field=models.TextField(blank=True, verbose_name='rejection reason'),
        ),
        migrations.AddField(
            model_name='propertyimage',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='active'),
        ),
        migrations.AddField(
            model_name='propertyimage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Review'), ('active', 'Active'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('inactive', 'Inactive')], default='pending', max_length=20, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='property',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='propertyimage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='propertyimage',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['city', 'country', 'status'], name='properties__city_fd2c4e_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['minimum_price', 'maximum_price'], name='properties__minimum_891083_idx'),
        ),
        migrations.AddField(
            model_name='propertyavailability',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='properties.property'),
        ),
        migrations.AddIndex(
            model_name='propertyavailability',
            index=models.Index(fields=['property', 'date'], name='properties__propert_b456d0_idx'),
        ),
        migrations.AddIndex(
            model_name='propertyavailability',
            index=models.Index(fields=['property', 'date', 'is_available'], name='properties__propert_7f65c1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='propertyavailability',
            unique_together={('property', 'date')},
        ),
    ]
