# Generated by Django 5.2.11 on 2026-03-02 17:05

import django.core.validators
import properties.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_uuidtaggeditem'),
        ('properties', '0004_alter_property_tags'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='propertyimage',
            options={'ordering': ['-is_primary', 'display_order', 'created_at'], 'verbose_name': 'property image', 'verbose_name_plural': 'property images'},
        ),
        migrations.AddField(
            model_name='propertyimage',
            name='file_size',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True, verbose_name='file size'),
        ),
        migrations.AddField(
            model_name='propertyimage',
            name='height',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True, verbose_name='height'),
        ),
        migrations.AddField(
            model_name='propertyimage',
            name='is_processed',
            field=models.BooleanField(default=False, verbose_name='processed'),
        ),
        migrations.AddField(
            model_name='propertyimage',
            name='processing_error',
            field=models.TextField(blank=True, verbose_name='processing error'),
        ),
        migrations.AddField(
            model_name='propertyimage',
            name='thumbnail_url',
            field=models.URLField(blank=True, editable=False, verbose_name='thumbnail URL'),
        ),
        migrations.AddField(
            model_name='propertyimage',
            name='width',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True, verbose_name='width'),
        ),
        migrations.AlterField(
            model_name='propertyimage',
            name='display_order',
            field=models.PositiveIntegerField(db_index=True, default=0, validators=[django.core.validators.MaxValueValidator(999)], verbose_name='display order'),
        ),
        migrations.AlterField(
            model_name='propertyimage',
            name='image',
            field=models.ImageField(help_text='Supported formats: JPG, PNG, GIF, WebP. Max 5MB.', upload_to=properties.models.property_image_upload_path, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='propertyimage',
            name='is_primary',
            field=models.BooleanField(db_index=True, default=False, verbose_name='primary image'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['owner', 'status'], name='properties__owner_i_30ec29_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['status', 'is_active', 'is_deleted'], name='properties__status_9c08ad_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['country', 'city'], name='properties__country_f5203b_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['status', 'created_at'], name='properties__status_8e4eb2_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['is_verified', 'status'], name='properties__is_veri_9c6361_idx'),
        ),
        migrations.AddIndex(
            model_name='propertyimage',
            index=models.Index(fields=['property', 'is_primary'], name='properties__propert_6e4e30_idx'),
        ),
        migrations.AddIndex(
            model_name='propertyimage',
            index=models.Index(fields=['property', 'display_order'], name='properties__propert_020873_idx'),
        ),
        migrations.AddConstraint(
            model_name='property',
            constraint=models.CheckConstraint(condition=models.Q(('minimum_price__isnull', True), ('maximum_price__isnull', True), ('minimum_price__lte', models.F('maximum_price')), _connector='OR'), name='property_price_range_valid'),
        ),
        migrations.AddConstraint(
            model_name='property',
            constraint=models.CheckConstraint(condition=models.Q(('minimum_price__isnull', True), ('minimum_price__gte', 0), _connector='OR'), name='property_min_price_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='property',
            constraint=models.CheckConstraint(condition=models.Q(('maximum_price__isnull', True), ('maximum_price__gte', 0), _connector='OR'), name='property_max_price_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='property',
            constraint=models.CheckConstraint(condition=models.Q(('commission_rate__gte', 0), ('commission_rate__lte', 100)), name='property_commission_rate_valid'),
        ),
    ]
