# Generated by Django 5.2.11 on 2026-03-02 18:31

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_property_create_flow_enhancements'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomtype',
            name='base_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price per night in USD', max_digits=10, null=True, verbose_name='base price per night'),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='quantity_available',
            field=models.PositiveSmallIntegerField(default=1, help_text='Number of rooms of this type available', validators=[django.core.validators.MaxValueValidator(1000)], verbose_name='quantity available'),
        ),
        migrations.CreateModel(
            name='PropertyActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='activity name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('activity_type', models.CharField(choices=[('tour', 'Guided Tour'), ('safari', 'Safari'), ('hiking', 'Hiking/Trekking'), ('water', 'Water Activity'), ('cultural', 'Cultural Experience'), ('wildlife', 'Wildlife Viewing'), ('dining', 'Dining Experience'), ('spa', 'Spa/Wellness'), ('adventure', 'Adventure Activity'), ('other', 'Other')], default='tour', max_length=50, verbose_name='activity type')),
                ('price_per_person', models.DecimalField(blank=True, decimal_places=2, help_text='Price per person in USD', max_digits=10, null=True, verbose_name='price per person')),
                ('duration', models.CharField(blank=True, help_text='e.g., 3 hours, Half-day, Full day', max_length=100, verbose_name='duration')),
                ('min_participants', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='minimum participants')),
                ('max_participants', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(500)], verbose_name='maximum participants')),
                ('availability', models.CharField(choices=[('daily', 'Daily'), ('weekdays', 'Weekdays Only'), ('weekends', 'Weekends Only'), ('on_request', 'On Request')], default='daily', max_length=20, verbose_name='availability')),
                ('difficulty', models.CharField(choices=[('easy', 'Easy (All ages)'), ('moderate', 'Moderate'), ('challenging', 'Challenging'), ('extreme', 'Extreme')], default='moderate', max_length=20, verbose_name='difficulty level')),
                ('included', models.TextField(blank=True, help_text='e.g., Guide, refreshments, equipment...', verbose_name="what's included")),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='display order')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_activities', to='properties.property')),
            ],
            options={
                'verbose_name': 'property activity',
                'verbose_name_plural': 'property activities',
                'ordering': ['display_order', 'name'],
            },
        ),
    ]
