# Generated by Django 5.2.11 on 2026-03-02 18:56

import django.core.validators
import django.db.models.deletion
import properties.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_add_roomtype_price_and_activity'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomTypeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Room photo. Supported formats: JPG, PNG, WebP. Max 5MB.', upload_to=properties.models.room_type_image_upload_path, verbose_name='image')),
                ('caption', models.CharField(blank=True, help_text='e.g., "Bedroom view", "En-suite bathroom", "Balcony overlooking garden"', max_length=255, verbose_name='caption')),
                ('is_primary', models.BooleanField(db_index=True, default=False, help_text='Main photo shown in room listings', verbose_name='primary image')),
                ('display_order', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(99)], verbose_name='display order')),
                ('width', models.PositiveIntegerField(blank=True, editable=False, null=True, verbose_name='width')),
                ('height', models.PositiveIntegerField(blank=True, editable=False, null=True, verbose_name='height')),
                ('file_size', models.PositiveIntegerField(blank=True, editable=False, null=True, verbose_name='file size')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='properties.roomtype')),
            ],
            options={
                'verbose_name': 'room type image',
                'verbose_name_plural': 'room type images',
                'ordering': ['-is_primary', 'display_order', 'created_at'],
                'indexes': [models.Index(fields=['room_type', 'is_primary'], name='properties__room_ty_916097_idx'), models.Index(fields=['room_type', 'display_order'], name='properties__room_ty_bae664_idx')],
            },
        ),
    ]
