# Generated by Django 5.2.11 on 2026-03-06 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0007_add_room_type_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='listing_fee_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Optional host listing fee amount.', max_digits=10, null=True, verbose_name='listing fee amount'),
        ),
        migrations.AddField(
            model_name='property',
            name='listing_fee_currency',
            field=models.CharField(choices=[('USD', 'US Dollar'), ('ZWL', 'Zimbabwe Gold')], default='USD', max_length=3, verbose_name='listing fee currency'),
        ),
        migrations.AddField(
            model_name='property',
            name='listing_payment_method',
            field=models.CharField(blank=True, choices=[('card', 'Card (3D Secure)'), ('paynow', 'Paynow'), ('ecocash', 'EcoCash'), ('bank_transfer', 'Bank Transfer')], max_length=30, verbose_name='listing payment method'),
        ),
        migrations.AddField(
            model_name='property',
            name='listing_payment_reference',
            field=models.CharField(blank=True, max_length=100, verbose_name='listing payment reference'),
        ),
        migrations.AddField(
            model_name='property',
            name='listing_payment_status',
            field=models.CharField(choices=[('not_required', 'Not Required'), ('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed')], default='not_required', max_length=20, verbose_name='listing payment status'),
        ),
        migrations.AddField(
            model_name='property',
            name='requires_listing_payment',
            field=models.BooleanField(default=False, help_text='Optional upfront payment from host for priority listing review.', verbose_name='requires listing payment'),
        ),
    ]
