# Generated by Django 5.2.11 on 2026-03-06 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0009_propertyfavorite'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='propertyfavorite',
            new_name='properties__user_id_76fc16_idx',
            old_name='properties_p_user_id_b648fe_idx',
        ),
        migrations.RenameIndex(
            model_name='propertyfavorite',
            new_name='properties__propert_3b0a97_idx',
            old_name='properties_p_propert_ad9ec2_idx',
        ),
    ]
