# Generated by Django 5.2.11 on 2026-02-25 20:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('bookings', '0001_initial'),
        ('car_rentals', '0001_initial'),
        ('flights', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessDashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_spent', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='total spent')),
                ('total_bookings', models.PositiveIntegerField(default=0, verbose_name='total bookings')),
                ('active_travelers', models.PositiveIntegerField(default=0, verbose_name='active travelers')),
                ('monthly_spending', models.JSONField(blank=True, default=dict, verbose_name='monthly spending')),
                ('monthly_bookings', models.JSONField(blank=True, default=dict, verbose_name='monthly bookings')),
                ('top_destinations', models.JSONField(blank=True, default=list, verbose_name='top destinations')),
                ('compliance_rate', models.DecimalField(decimal_places=2, default=100, help_text='Percentage of bookings compliant with policy', max_digits=5, verbose_name='compliance rate')),
                ('total_savings', models.DecimalField(decimal_places=2, default=0, help_text='Savings from negotiated rates and policies', max_digits=15, verbose_name='total savings')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='last updated')),
            ],
            options={
                'verbose_name': 'business dashboard',
                'verbose_name_plural': 'business dashboards',
            },
        ),
        migrations.CreateModel(
            name='BusinessDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='department name')),
                ('code', models.CharField(max_length=50, verbose_name='department code')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('monthly_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='monthly budget')),
                ('requires_approval', models.BooleanField(default=True, verbose_name='requires approval')),
                ('approval_level', models.PositiveSmallIntegerField(default=1, help_text='Hierarchy level for approval chain', verbose_name='approval level')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'business department',
                'verbose_name_plural': 'business departments',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BusinessEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(blank=True, max_length=50, verbose_name='employee ID')),
                ('job_title', models.CharField(blank=True, max_length=100, verbose_name='job title')),
                ('can_book', models.BooleanField(default=True, verbose_name='can book')),
                ('can_approve', models.BooleanField(default=False, verbose_name='can approve')),
                ('approval_limit', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum booking amount they can approve', max_digits=12, null=True, verbose_name='approval limit')),
                ('travel_class', models.CharField(blank=True, choices=[('economy', 'Economy'), ('premium_economy', 'Premium Economy'), ('business', 'Business'), ('first', 'First Class')], max_length=50, verbose_name='travel class')),
                ('hotel_preference', models.JSONField(blank=True, default=dict, help_text='Preferred hotel chains, star ratings, etc.', verbose_name='hotel preference')),
                ('car_rental_preference', models.JSONField(blank=True, default=dict, help_text='Preferred car rental companies, car types, etc.', verbose_name='car rental preference')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'business employee',
                'verbose_name_plural': 'business employees',
            },
        ),
        migrations.CreateModel(
            name='BusinessExpenseReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_number', models.CharField(max_length=50, unique=True, verbose_name='report number')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('start_date', models.DateField(verbose_name='start date')),
                ('end_date', models.DateField(verbose_name='end date')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='total amount')),
                ('approved_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='approved amount')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('paid', 'Paid')], default='draft', max_length=20, verbose_name='status')),
                ('approval_date', models.DateTimeField(blank=True, null=True, verbose_name='approval date')),
                ('approval_notes', models.TextField(blank=True, verbose_name='approval notes')),
                ('paid_date', models.DateField(blank=True, null=True, verbose_name='paid date')),
                ('payment_reference', models.CharField(blank=True, max_length=100, verbose_name='payment reference')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='submitted at')),
            ],
            options={
                'verbose_name': 'business expense report',
                'verbose_name_plural': 'business expense reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BusinessTravelPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_flight_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='maximum flight cost')),
                ('preferred_airlines', models.JSONField(blank=True, default=list, verbose_name='preferred airlines')),
                ('allowed_classes', models.JSONField(default=list, help_text='List of allowed flight classes', verbose_name='allowed classes')),
                ('advance_booking_days', models.PositiveSmallIntegerField(default=14, help_text='Minimum days before travel to book', verbose_name='advance booking days')),
                ('max_hotel_cost_per_night', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='maximum hotel cost per night')),
                ('preferred_hotel_chains', models.JSONField(blank=True, default=list, verbose_name='preferred hotel chains')),
                ('max_star_rating', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='maximum star rating')),
                ('max_car_rental_cost_per_day', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='maximum car rental cost per day')),
                ('preferred_car_types', models.JSONField(blank=True, default=list, verbose_name='preferred car types')),
                ('insurance_required', models.BooleanField(default=True, verbose_name='insurance required')),
                ('daily_meal_allowance', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='daily meal allowance')),
                ('requires_receipts', models.BooleanField(default=True, verbose_name='requires receipts')),
                ('expense_report_deadline', models.PositiveSmallIntegerField(default=30, help_text='Days after travel to submit expenses', verbose_name='expense report deadline')),
                ('approval_levels', models.JSONField(default=list, help_text='Approval workflow configuration', verbose_name='approval levels')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'business travel policy',
                'verbose_name_plural': 'business travel policies',
            },
        ),
        migrations.CreateModel(
            name='ExpenseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='date')),
                ('category', models.CharField(choices=[('accommodation', 'Accommodation'), ('transportation', 'Transportation'), ('meals', 'Meals'), ('entertainment', 'Entertainment'), ('supplies', 'Supplies'), ('other', 'Other')], max_length=50, verbose_name='category')),
                ('description', models.CharField(max_length=255, verbose_name='description')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='amount')),
                ('currency', models.CharField(default='USD', max_length=3, verbose_name='currency')),
                ('exchange_rate', models.DecimalField(decimal_places=6, default=1, max_digits=10, verbose_name='exchange rate')),
                ('converted_amount', models.DecimalField(decimal_places=2, help_text='Amount in report currency', max_digits=10, verbose_name='converted amount')),
                ('receipt_image', models.ImageField(blank=True, null=True, upload_to='expense_receipts/', verbose_name='receipt image')),
                ('receipt_number', models.CharField(blank=True, max_length=100, verbose_name='receipt number')),
                ('business_purpose', models.TextField(blank=True, verbose_name='business purpose')),
                ('is_approved', models.BooleanField(default=False, verbose_name='approved')),
                ('approval_notes', models.TextField(blank=True, verbose_name='approval notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'expense item',
                'verbose_name_plural': 'expense items',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='BusinessBookingApproval',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('approval_level', models.PositiveSmallIntegerField(default=1, verbose_name='approval level')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('escalated', 'Escalated')], default='pending', max_length=20, verbose_name='status')),
                ('decision_notes', models.TextField(blank=True, verbose_name='decision notes')),
                ('decision_date', models.DateTimeField(blank=True, null=True, verbose_name='decision date')),
                ('escalation_reason', models.TextField(blank=True, verbose_name='escalation reason')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals_to_review', to=settings.AUTH_USER_MODEL)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='bookings.booking')),
                ('business_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_approvals', to='accounts.businessaccount')),
                ('car_rental_booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='car_rentals.carrentalbooking')),
                ('escalated_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escalated_approvals', to=settings.AUTH_USER_MODEL)),
                ('flight_booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='flights.flightbooking')),
            ],
            options={
                'verbose_name': 'business booking approval',
                'verbose_name_plural': 'business booking approvals',
                'ordering': ['-created_at'],
            },
        ),
    ]
