# Generated by Django 5.2.11 on 2026-02-25 20:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('business', '0001_initial'),
        ('tours', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='businessbookingapproval',
            name='tour_booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='tours.tourbooking'),
        ),
        migrations.AddField(
            model_name='businessdashboard',
            name='business_account',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard', to='accounts.businessaccount'),
        ),
        migrations.AddField(
            model_name='businessdepartment',
            name='business_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='accounts.businessaccount'),
        ),
        migrations.AddField(
            model_name='businessdepartment',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_departments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='businessemployee',
            name='business_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='accounts.businessaccount'),
        ),
        migrations.AddField(
            model_name='businessemployee',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='business.businessdepartment'),
        ),
        migrations.AddField(
            model_name='businessemployee',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='business_employee', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='businessbookingapproval',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_approvals', to='business.businessemployee'),
        ),
        migrations.AddField(
            model_name='businessexpensereport',
            name='approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_expense_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='businessexpensereport',
            name='business_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_reports', to='accounts.businessaccount'),
        ),
        migrations.AddField(
            model_name='businessexpensereport',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_reports', to='business.businessemployee'),
        ),
        migrations.AddField(
            model_name='businesstravelpolicy',
            name='business_account',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='business_travel_policy', to='accounts.businessaccount'),
        ),
        migrations.AddField(
            model_name='expenseitem',
            name='expense_report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='business.businessexpensereport'),
        ),
        migrations.AlterUniqueTogether(
            name='businessemployee',
            unique_together={('business_account', 'user')},
        ),
    ]
