# Generated by Django 5.2.11 on 2026-02-28 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='aiassistantinsight',
            new_name='ai_assistan_insight_3df152_idx',
            old_name='ai_assista_insight_39927a_idx',
        ),
        migrations.RenameIndex(
            model_name='aiassistantinsight',
            new_name='ai_assistan_created_79369c_idx',
            old_name='ai_assista_created_77a448_idx',
        ),
        migrations.RenameIndex(
            model_name='supportthread',
            new_name='ai_assistan_status_54dae8_idx',
            old_name='ai_assista_status_0d14d9_idx',
        ),
        migrations.RenameIndex(
            model_name='supportthread',
            new_name='ai_assistan_source_1aad3f_idx',
            old_name='ai_assista_source_183c7d_idx',
        ),
        migrations.RenameIndex(
            model_name='supportthread',
            new_name='ai_assistan_custome_01108f_idx',
            old_name='ai_assista_customer_a8b82d_idx',
        ),
    ]
