# Generated by Django 5.2.11 on 2026-03-02 16:42

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0002_rename_ai_assista_insight_39927a_idx_ai_assistan_insight_3df152_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIRateLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(choices=[('free', 'Free'), ('premium', 'Premium'), ('enterprise', 'Enterprise'), ('unlimited', 'Unlimited')], default='free', max_length=20)),
                ('daily_request_limit', models.PositiveIntegerField(default=10)),
                ('daily_token_limit', models.PositiveIntegerField(default=5000)),
                ('daily_cost_limit_usd', models.DecimalField(decimal_places=2, default=Decimal('0.50'), max_digits=6)),
                ('monthly_request_limit', models.PositiveIntegerField(default=200)),
                ('monthly_token_limit', models.PositiveIntegerField(default=100000)),
                ('monthly_cost_limit_usd', models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=8)),
                ('is_blocked', models.BooleanField(default=False)),
                ('block_reason', models.CharField(blank=True, max_length=255)),
                ('blocked_until', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_rate_limit', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI Rate Limit',
                'verbose_name_plural': 'AI Rate Limits',
            },
        ),
        migrations.CreateModel(
            name='AIUsageRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=100)),
                ('operation', models.CharField(max_length=100)),
                ('prompt_name', models.CharField(blank=True, max_length=100)),
                ('prompt_version', models.CharField(blank=True, max_length=20)),
                ('prompt_tokens', models.PositiveIntegerField(default=0)),
                ('completion_tokens', models.PositiveIntegerField(default=0)),
                ('total_tokens', models.PositiveIntegerField(default=0)),
                ('prompt_cost_usd', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=10)),
                ('completion_cost_usd', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=10)),
                ('total_cost_usd', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=10)),
                ('latency_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('success', models.BooleanField(default=True)),
                ('error_type', models.CharField(blank=True, max_length=100)),
                ('request_metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_usage_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConversationMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System')], max_length=20)),
                ('content', models.TextField()),
                ('token_count', models.PositiveIntegerField(default=0)),
                ('model_used', models.CharField(blank=True, max_length=100)),
                ('prompt_name', models.CharField(blank=True, max_length=100)),
                ('latency_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('attachments', models.JSONField(blank=True, default=list)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ai_assistant.supportthread')),
                ('usage_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversation_messages', to='ai_assistant.aiusagerecord')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='AITaskResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('task_id', models.CharField(max_length=255, unique=True)),
                ('task_type', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('input_data', models.JSONField(default=dict)),
                ('result_data', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('provider', models.CharField(blank=True, max_length=50)),
                ('latency_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('usage', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_task_results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['task_id'], name='ai_assistan_task_id_6cce70_idx'), models.Index(fields=['user', 'status'], name='ai_assistan_user_id_ea264e_idx'), models.Index(fields=['expires_at'], name='ai_assistan_expires_445747_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='aiusagerecord',
            index=models.Index(fields=['user', 'created_at'], name='ai_assistan_user_id_0d7915_idx'),
        ),
        migrations.AddIndex(
            model_name='aiusagerecord',
            index=models.Index(fields=['operation', 'created_at'], name='ai_assistan_operati_4508e7_idx'),
        ),
        migrations.AddIndex(
            model_name='aiusagerecord',
            index=models.Index(fields=['provider', 'model'], name='ai_assistan_provide_4340fc_idx'),
        ),
        migrations.AddIndex(
            model_name='aiusagerecord',
            index=models.Index(fields=['created_at'], name='ai_assistan_created_42b03d_idx'),
        ),
        migrations.AddIndex(
            model_name='conversationmessage',
            index=models.Index(fields=['thread', 'created_at'], name='ai_assistan_thread__e8dede_idx'),
        ),
        migrations.AddIndex(
            model_name='conversationmessage',
            index=models.Index(fields=['role'], name='ai_assistan_role_8813b9_idx'),
        ),
    ]
