# Generated by Django 5.2.11 on 2026-03-01 19:57

import taggit.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_uuidtaggeditem'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        ('tours', '0002_tour_capacity_tour_deleted_at_tour_deleted_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='core.UUIDTaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
