# Generated by Django 5.2.11 on 2026-03-03 19:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0003_alter_tour_tags'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='touroperator',
            name='user',
            field=models.ForeignKey(blank=True, help_text='User who owns/manages this tour operator account', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tour_operators', to=settings.AUTH_USER_MODEL),
        ),
    ]
