# Generated by Django 5.2.11 on 2026-02-26 22:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLogEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('content_type', models.CharField(max_length=255, verbose_name='content type')),
                ('object_id', models.UUIDField(verbose_name='object ID')),
                ('object_repr', models.CharField(max_length=500, verbose_name='object representation')),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('restore', 'Restore'), ('approve', 'Approve'), ('reject', 'Reject'), ('cancel', 'Cancel'), ('complete', 'Complete'), ('other', 'Other')], max_length=20, verbose_name='action')),
                ('changes', models.JSONField(default=dict, verbose_name='changes')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP address')),
                ('user_agent', models.TextField(blank=True, verbose_name='user agent')),
                ('request_id', models.CharField(blank=True, max_length=36, verbose_name='request ID')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'audit log entry',
                'verbose_name_plural': 'audit log entries',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['object_id', 'action'], name='core_auditl_object__21d8cd_idx'), models.Index(fields=['user', 'created_at'], name='core_auditl_user_id_9163de_idx'), models.Index(fields=['content_type', 'created_at'], name='core_auditl_content_341b8f_idx')],
            },
        ),
    ]
