# Generated by Django 5.2.11 on 2026-03-14 11:09

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('car_rentals', '0001_initial'),
        ('properties', '0001_initial'),
        ('tours', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='active')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted at')),
                ('check_in_date', models.DateField(verbose_name='check-in date')),
                ('check_out_date', models.DateField(verbose_name='check-out date')),
                ('guests', models.PositiveIntegerField(default=1, verbose_name='number of guests')),
                ('special_requests', models.TextField(blank=True, help_text='Any special requests or preferences', verbose_name='special requests')),
                ('price_per_night', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='price per night')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='total amount')),
                ('commission_type', models.CharField(choices=[('local', 'Local (Zimbabwe)'), ('away', 'Away')], default='away', max_length=20, verbose_name='commission type')),
                ('commission_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Platform commission percentage applied to this booking.', max_digits=5, verbose_name='commission rate')),
                ('commission_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='commission amount')),
                ('host_payout_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='host payout amount')),
                ('payment_option', models.CharField(blank=True, choices=[('card', 'Card (3D Secure)'), ('paynow', 'Paynow'), ('ecocash', 'EcoCash'), ('bank_transfer', 'Bank Transfer')], max_length=30, verbose_name='payment option')),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed')], default='pending', max_length=20, verbose_name='payment status')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', max_length=20, verbose_name='status')),
                ('cancellation_reason', models.TextField(blank=True, verbose_name='cancellation reason')),
                ('car', models.ForeignKey(blank=True, help_text='Car being booked', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unified_bookings', to='car_rentals.car')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_soft_deleted', to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(blank=True, help_text='Property being booked', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unified_bookings', to='properties.property')),
                ('room_type', models.ForeignKey(blank=True, help_text='Selected room type for property bookings', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='properties.roomtype')),
                ('tour', models.ForeignKey(blank=True, help_text='Tour being booked', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unified_bookings', to='tours.tour')),
                ('tour_schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unified_bookings', to='tours.tourschedule')),
                ('user', models.ForeignKey(help_text='User who made the booking', on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'booking',
                'verbose_name_plural': 'bookings',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='bookings_bo_user_id_69a5d5_idx'), models.Index(fields=['property', 'check_in_date', 'check_out_date'], name='bookings_bo_propert_a3c1f4_idx'), models.Index(fields=['room_type', 'check_in_date', 'check_out_date'], name='bookings_bo_room_ty_a911d5_idx'), models.Index(fields=['car', 'check_in_date', 'check_out_date'], name='bookings_bo_car_id_a48437_idx'), models.Index(fields=['tour', 'check_in_date'], name='bookings_bo_tour_id_4c279e_idx'), models.Index(fields=['status', 'check_in_date'], name='bookings_bo_status_4382c8_idx')],
            },
        ),
    ]
