# Generated by Django 5.2.11 on 2026-02-26 13:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_initial'),
        ('properties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-created_at'], 'verbose_name': 'booking', 'verbose_name_plural': 'bookings'},
        ),
        migrations.AddField(
            model_name='booking',
            name='cancellation_reason',
            field=models.TextField(blank=True, verbose_name='cancellation reason'),
        ),
        migrations.AddField(
            model_name='booking',
            name='price_per_night',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='price per night'),
        ),
        migrations.AddField(
            model_name='booking',
            name='special_requests',
            field=models.TextField(blank=True, help_text='Any special requests or preferences', verbose_name='special requests'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='check_in_date',
            field=models.DateField(verbose_name='check-in date'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='check_out_date',
            field=models.DateField(verbose_name='check-out date'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='guests',
            field=models.PositiveIntegerField(default=1, verbose_name='number of guests'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='property',
            field=models.ForeignKey(help_text='Property being booked', on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='properties.property'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', max_length=20, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='total amount'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(help_text='User who made the booking', on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['user', 'status'], name='bookings_bo_user_id_69a5d5_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['property', 'check_in_date', 'check_out_date'], name='bookings_bo_propert_a3c1f4_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['status', 'check_in_date'], name='bookings_bo_status_4382c8_idx'),
        ),
    ]
