# Generated by Django 5.2.11 on 2026-02-28 10:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_alter_booking_options_booking_cancellation_reason_and_more'),
        ('car_rentals', '0005_caravailability_car_daily_price_car_deleted_at_and_more'),
        ('properties', '0002_alter_availability_available_rooms_and_more'),
        ('tours', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='car',
            field=models.ForeignKey(blank=True, help_text='Car being booked', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unified_bookings', to='car_rentals.car'),
        ),
        migrations.AddField(
            model_name='booking',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='deleted at'),
        ),
        migrations.AddField(
            model_name='booking',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_soft_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='booking',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='active'),
        ),
        migrations.AddField(
            model_name='booking',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, verbose_name='deleted'),
        ),
        migrations.AddField(
            model_name='booking',
            name='tour',
            field=models.ForeignKey(blank=True, help_text='Tour being booked', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unified_bookings', to='tours.tour'),
        ),
        migrations.AddField(
            model_name='booking',
            name='tour_schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unified_bookings', to='tours.tourschedule'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='booking',
            name='property',
            field=models.ForeignKey(blank=True, help_text='Property being booked', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unified_bookings', to='properties.property'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='total amount'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['car', 'check_in_date', 'check_out_date'], name='bookings_bo_car_id_a48437_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['tour', 'check_in_date'], name='bookings_bo_tour_id_4c279e_idx'),
        ),
    ]
