# Generated by Django 5.2.11 on 2026-03-06 10:19

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_booking_car_booking_deleted_at_booking_deleted_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='commission_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='commission amount'),
        ),
        migrations.AddField(
            model_name='booking',
            name='commission_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Platform commission percentage applied to this booking.', max_digits=5, verbose_name='commission rate'),
        ),
        migrations.AddField(
            model_name='booking',
            name='commission_type',
            field=models.CharField(choices=[('local', 'Local (Zimbabwe)'), ('away', 'Away')], default='away', max_length=20, verbose_name='commission type'),
        ),
        migrations.AddField(
            model_name='booking',
            name='host_payout_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='host payout amount'),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_option',
            field=models.CharField(blank=True, choices=[('card', 'Card (3D Secure)'), ('paynow', 'Paynow'), ('ecocash', 'EcoCash'), ('bank_transfer', 'Bank Transfer')], max_length=30, verbose_name='payment option'),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed')], default='pending', max_length=20, verbose_name='payment status'),
        ),
    ]
