# Generated by Django 5.2.11 on 2026-02-25 20:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        ('car_rentals', '0001_initial'),
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='notification type')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='code')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('channels', models.JSONField(default=list, help_text='List of channels for this notification type', verbose_name='channels')),
                ('email_subject', models.CharField(blank=True, max_length=255, verbose_name='email subject')),
                ('email_template', models.TextField(blank=True, verbose_name='email template')),
                ('sms_template', models.TextField(blank=True, verbose_name='SMS template')),
                ('push_template', models.TextField(blank=True, verbose_name='push template')),
                ('in_app_template', models.TextField(blank=True, verbose_name='in-app template')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('is_required', models.BooleanField(default=False, help_text='Cannot be disabled by user', verbose_name='required')),
                ('priority', models.PositiveSmallIntegerField(default=1, help_text='Higher number = higher priority', verbose_name='priority')),
                ('default_enabled', models.BooleanField(default=True, verbose_name='enabled by default')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'notification type',
                'verbose_name_plural': 'notification types',
                'ordering': ['priority', 'code'],
            },
        ),
        migrations.CreateModel(
            name='PushNotificationDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_type', models.CharField(choices=[('ios', 'iOS'), ('android', 'Android'), ('web', 'Web')], max_length=20, verbose_name='device type')),
                ('device_token', models.CharField(max_length=255, unique=True, verbose_name='device token')),
                ('device_id', models.CharField(blank=True, max_length=255, verbose_name='device ID')),
                ('app_version', models.CharField(blank=True, max_length=50, verbose_name='app version')),
                ('os_version', models.CharField(blank=True, max_length=50, verbose_name='OS version')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('last_active', models.DateTimeField(auto_now=True, verbose_name='last active')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'push notification device',
                'verbose_name_plural': 'push notification devices',
            },
        ),
        migrations.CreateModel(
            name='SMSLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=50, verbose_name='phone number')),
                ('message', models.TextField(verbose_name='message')),
                ('message_id', models.CharField(blank=True, max_length=255, verbose_name='message ID')),
                ('provider', models.CharField(blank=True, max_length=100, verbose_name='provider')),
                ('provider_response', models.JSONField(blank=True, default=dict, verbose_name='provider response')),
                ('cost', models.DecimalField(decimal_places=4, default=0, max_digits=8, verbose_name='cost')),
                ('currency', models.CharField(default='USD', max_length=3, verbose_name='currency')),
                ('delivered', models.BooleanField(default=False, verbose_name='delivered')),
                ('delivery_timestamp', models.DateTimeField(blank=True, null=True, verbose_name='delivery timestamp')),
                ('error_code', models.CharField(blank=True, max_length=100, verbose_name='error code')),
                ('error_message', models.TextField(blank=True, verbose_name='error message')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'SMS log',
                'verbose_name_plural': 'SMS logs',
            },
        ),
        migrations.CreateModel(
            name='UserNotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_enabled', models.BooleanField(default=True, verbose_name='email enabled')),
                ('sms_enabled', models.BooleanField(default=True, verbose_name='SMS enabled')),
                ('push_enabled', models.BooleanField(default=True, verbose_name='push enabled')),
                ('in_app_enabled', models.BooleanField(default=True, verbose_name='in-app enabled')),
                ('frequency', models.CharField(choices=[('immediate', 'Immediate'), ('daily', 'Daily Digest'), ('weekly', 'Weekly Digest'), ('disabled', 'Disabled')], default='immediate', max_length=20, verbose_name='frequency')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'user notification preference',
                'verbose_name_plural': 'user notification preferences',
            },
        ),
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='template name')),
                ('template_type', models.CharField(choices=[('booking_confirmation', 'Booking Confirmation'), ('booking_cancellation', 'Booking Cancellation'), ('payment_receipt', 'Payment Receipt'), ('password_reset', 'Password Reset'), ('welcome', 'Welcome Email'), ('promotional', 'Promotional'), ('review_reminder', 'Review Reminder'), ('security_alert', 'Security Alert')], max_length=50, verbose_name='template type')),
                ('language', models.CharField(default='en', max_length=10, verbose_name='language')),
                ('subject', models.CharField(max_length=255, verbose_name='subject')),
                ('html_content', models.TextField(verbose_name='HTML content')),
                ('plain_text_content', models.TextField(blank=True, verbose_name='plain text content')),
                ('variables', models.JSONField(default=list, help_text='List of available template variables', verbose_name='variables')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('is_default', models.BooleanField(default=False, verbose_name='default')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'email template',
                'verbose_name_plural': 'email templates',
                'ordering': ['template_type', 'language'],
                'unique_together': {('template_type', 'language')},
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('push', 'Push Notification'), ('in_app', 'In-App Notification'), ('webhook', 'Webhook')], max_length=20, verbose_name='channel')),
                ('subject', models.CharField(blank=True, max_length=255, verbose_name='subject')),
                ('message', models.TextField(verbose_name='message')),
                ('context', models.JSONField(blank=True, default=dict, help_text='Context data used to render the notification', verbose_name='context')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sending', 'Sending'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('read', 'Read'), ('failed', 'Failed'), ('bounced', 'Bounced')], default='pending', max_length=20, verbose_name='status')),
                ('delivery_attempts', models.PositiveSmallIntegerField(default=0, verbose_name='delivery attempts')),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True, verbose_name='last attempt at')),
                ('error_message', models.TextField(blank=True, verbose_name='error message')),
                ('error_code', models.CharField(blank=True, max_length=100, verbose_name='error code')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='sent at')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='delivered at')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='read at')),
                ('related_booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='bookings.booking')),
                ('related_car_rental_booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='car_rentals.carrentalbooking')),
                ('related_flight_booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='flights.flightbooking')),
            ],
            options={
                'verbose_name': 'notification',
                'verbose_name_plural': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
