# Generated by Django 5.2.11 on 2026-03-01 21:00

from django.db import migrations


def seed_email_templates(apps, schema_editor):
        EmailTemplate = apps.get_model('notifications', 'EmailTemplate')

        templates = [
                {
                        'name': 'Booking Confirmation',
                        'template_type': 'booking_confirmation',
                        'language': 'en',
                        'subject': 'Booking confirmed: {{ property_name }} ({{ booking_reference }})',
                        'html_content': """
                                <table width="100%" cellpadding="0" cellspacing="0" style="font-family: 'Inter', Arial, sans-serif; background:#f4f6fb; padding:32px;">
                                    <tr>
                                        <td align="center">
                                            <table width="640" cellpadding="0" cellspacing="0" style="background:#ffffff; border-radius:16px; overflow:hidden;">
                                                <tr>
                                                    <td style="background:#0b1f2e; color:#f6b17a; padding:32px; text-align:center;">
                                                        <h1 style="margin:0; font-size:26px; letter-spacing:0.5px;">Marvel Safari</h1>
                                                        <p style="margin:4px 0 0; color:#e2e8f0; font-size:14px;">Booking confirmation</p>
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td style="padding:32px; color:#0f172a;">
                                                        <p style="font-size:16px; margin:0 0 16px;">Hi {{ user_name }},</p>
                                                        <p style="margin:0 0 24px; line-height:1.6;">Your stay at <strong>{{ property_name }}</strong> is confirmed. We are excited to host you and make sure everything feels seamless.</p>
                                                        <table width="100%" cellpadding="0" cellspacing="0" style="background:#f8fafc; border-radius:12px; padding:20px;">
                                                            <tr><td style="padding-bottom:12px;"><strong>Booking reference:</strong> {{ booking_reference }}</td></tr>
                                                            <tr><td style="padding-bottom:12px;"><strong>Check-in:</strong> {{ check_in_date }}</td></tr>
                                                            <tr><td style="padding-bottom:12px;"><strong>Check-out:</strong> {{ check_out_date }}</td></tr>
                                                            <tr><td><strong>Total:</strong> {{ booking_total }}</td></tr>
                                                        </table>
                                                        <p style="margin:24px 0;">
                                                            <a href="{{ manage_booking_url }}" style="background:#f6b17a; color:#0b1f2e; padding:12px 24px; border-radius:999px; text-decoration:none; font-weight:600;">Manage booking</a>
                                                        </p>
                                                        <p style="font-size:14px; color:#475569;">Need to adjust anything? Our concierge team is on standby at {{ support_email }}.</p>
                                                    </td>
                                                </tr>
                                            </table>
                                        </td>
                                    </tr>
                                </table>
                        """.strip(),
                        'plain_text_content': (
                                "Hi {{ user_name }},\n\n"
                                "Your stay at {{ property_name }} is confirmed.\n"
                                "Booking reference: {{ booking_reference }}\n"
                                "Check-in: {{ check_in_date }}\n"
                                "Check-out: {{ check_out_date }}\n"
                                "Total: {{ booking_total }}\n\n"
                                "Manage your booking: {{ manage_booking_url }}\n"
                                "Concierge support: {{ support_email }}"
                        ),
                        'variables': [
                                'user_name', 'property_name', 'booking_reference',
                                'check_in_date', 'check_out_date', 'booking_total',
                                'manage_booking_url', 'support_email'
                        ],
                        'is_active': True,
                        'is_default': True,
                },
                {
                        'name': 'Booking Cancellation',
                        'template_type': 'booking_cancellation',
                        'language': 'en',
                        'subject': 'Booking cancelled: {{ property_name }} ({{ booking_reference }})',
                        'html_content': """
                                <table width="100%" cellpadding="0" cellspacing="0" style="font-family: 'Inter', Arial, sans-serif; background:#fff7ed; padding:32px;">
                                    <tr>
                                        <td align="center">
                                            <table width="640" cellpadding="0" cellspacing="0" style="background:#ffffff; border-radius:16px; border:1px solid #fed7aa;">
                                                <tr>
                                                    <td style="padding:32px; color:#9a3412;">
                                                        <h2 style="margin:0 0 12px;">Your booking has been cancelled</h2>
                                                        <p style="margin:0 0 20px; color:#7c2d12;">Reference {{ booking_reference }} for {{ property_name }} is now cancelled.</p>
                                                        <table width="100%" cellpadding="0" cellspacing="0" style="background:#fff7ed; border-radius:12px; padding:20px;">
                                                            <tr><td><strong>Original stay:</strong> {{ check_in_date }} – {{ check_out_date }}</td></tr>
                                                            <tr><td><strong>Guest:</strong> {{ user_name }}</td></tr>
                                                        </table>
                                                        <p style="margin:24px 0; color:#7c2d12;">If this was unexpected, reach out immediately and we will help reinstate your reservation if possible.</p>
                                                        <p style="margin:0; font-size:14px; color:#7c2d12;">Concierge desk • {{ support_email }}</p>
                                                    </td>
                                                </tr>
                                            </table>
                                        </td>
                                    </tr>
                                </table>
                        """.strip(),
                        'plain_text_content': (
                                "Booking {{ booking_reference }} for {{ property_name }} has been cancelled.\n"
                                "Stay dates: {{ check_in_date }} – {{ check_out_date }}\n"
                                "Guest: {{ user_name }}\n\n"
                                "Questions? Contact {{ support_email }}."
                        ),
                        'variables': [
                                'user_name', 'property_name', 'booking_reference',
                                'check_in_date', 'check_out_date', 'support_email'
                        ],
                        'is_active': True,
                        'is_default': True,
                },
                {
                        'name': 'Payment Receipt',
                        'template_type': 'payment_receipt',
                        'language': 'en',
                        'subject': 'Payment receipt {{ payment_reference }}',
                        'html_content': """
                                <table width="100%" cellpadding="0" cellspacing="0" style="font-family: 'Inter', Arial, sans-serif; background:#f4f6fb; padding:32px;">
                                    <tr><td align="center">
                                        <table width="640" cellpadding="0" cellspacing="0" style="background:#ffffff; border-radius:16px;">
                                            <tr>
                                                <td style="padding:32px; color:#0f172a;">
                                                    <h2 style="margin:0 0 12px;">Payment received</h2>
                                                    <p style="margin:0 0 16px; color:#475569;">Receipt {{ payment_reference }} for {{ item_name }}</p>
                                                    <table width="100%" cellpadding="0" cellspacing="0" style="border:1px solid #e2e8f0; border-radius:12px;">
                                                        <tr>
                                                            <td style="padding:16px;">Amount</td>
                                                            <td style="padding:16px; font-weight:600; text-align:right;">{{ amount }} {{ currency }}</td>
                                                        </tr>
                                                        <tr style="background:#f8fafc;">
                                                            <td style="padding:16px;">Date</td>
                                                            <td style="padding:16px; text-align:right;">{{ payment_date }}</td>
                                                        </tr>
                                                    </table>
                                                    <p style="margin:24px 0;">
                                                        <a href="{{ invoice_url }}" style="color:#0b1f2e; font-weight:600; text-decoration:none;">Download invoice →</a>
                                                    </p>
                                                    <p style="font-size:14px; color:#475569;">Need help? {{ support_email }}</p>
                                                </td>
                                            </tr>
                                        </table>
                                    </td></tr>
                                </table>
                        """.strip(),
                        'plain_text_content': (
                                "Payment receipt {{ payment_reference }}\n"
                                "Item: {{ item_name }}\n"
                                "Amount: {{ amount }} {{ currency }}\n"
                                "Date: {{ payment_date }}\n\n"
                                "Invoice: {{ invoice_url }}\n"
                                "Support: {{ support_email }}"
                        ),
                        'variables': [
                                'user_name', 'payment_reference', 'item_name',
                                'amount', 'currency', 'payment_date',
                                'invoice_url', 'support_email'
                        ],
                        'is_active': True,
                        'is_default': True,
                },
                {
                        'name': 'Welcome Email',
                        'template_type': 'welcome',
                        'language': 'en',
                        'subject': 'Welcome aboard, {{ user_name }}',
                        'html_content': """
                                <table width="100%" cellpadding="0" cellspacing="0" style="font-family: 'Inter', Arial, sans-serif; background:#eef2ff; padding:32px;">
                                    <tr><td align="center">
                                        <table width="640" cellpadding="0" cellspacing="0" style="background:#ffffff; border-radius:16px;">
                                            <tr>
                                                <td style="padding:36px; text-align:center; color:#312e81;">
                                                    <h1 style="margin:0 0 12px;">Welcome to Marvel Safari</h1>
                                                    <p style="margin:0 0 24px; color:#4c1d95;">Your premium escapes now live in one dashboard.</p>
                                                    <a href="{{ dashboard_url }}" style="background:#312e81; color:#f8fafc; padding:14px 30px; border-radius:999px; text-decoration:none; font-weight:600;">Explore dashboard</a>
                                                    <p style="margin:24px 0 0; font-size:14px; color:#4c1d95;">Concierge: {{ support_email }}</p>
                                                </td>
                                            </tr>
                                        </table>
                                    </td></tr>
                                </table>
                        """.strip(),
                        'plain_text_content': (
                                "Welcome to Marvel Safari, {{ user_name }}!\n"
                                "Start exploring: {{ dashboard_url }}\n"
                                "Need help? {{ support_email }}"
                        ),
                        'variables': ['user_name', 'dashboard_url', 'support_email'],
                        'is_active': True,
                        'is_default': True,
                },
                {
                        'name': 'Review Reminder',
                        'template_type': 'review_reminder',
                        'language': 'en',
                        'subject': 'How was {{ property_name }}?',
                        'html_content': """
                                <table width="100%" cellpadding="0" cellspacing="0" style="font-family: 'Inter', Arial, sans-serif; background:#ecfccb; padding:32px;">
                                    <tr><td align="center">
                                        <table width="640" cellpadding="0" cellspacing="0" style="background:#ffffff; border-radius:16px;">
                                            <tr>
                                                <td style="padding:32px; color:#365314;">
                                                    <h2 style="margin:0 0 12px;">Share your stay</h2>
                                                    <p style="margin:0 0 20px;">Tell other travelers about your recent visit to {{ property_name }} on {{ stay_date }}.</p>
                                                    <a href="{{ review_url }}" style="display:inline-block; background:#65a30d; color:#f7fee7; padding:12px 26px; border-radius:999px; text-decoration:none; font-weight:600;">Leave a review</a>
                                                    <p style="margin:24px 0 0; font-size:14px; color:#4d7c0f;">Need anything else? {{ support_email }}</p>
                                                </td>
                                            </tr>
                                        </table>
                                    </td></tr>
                                </table>
                        """.strip(),
                        'plain_text_content': (
                                "Hope you enjoyed {{ property_name }} on {{ stay_date }}.\n"
                                "Share your thoughts: {{ review_url }}\n"
                                "Concierge: {{ support_email }}"
                        ),
                        'variables': ['user_name', 'property_name', 'stay_date', 'review_url', 'support_email'],
                        'is_active': True,
                        'is_default': True,
                },
                {
                        'name': 'Security Alert',
                        'template_type': 'security_alert',
                        'language': 'en',
                        'subject': 'Security alert: {{ action }}',
                        'html_content': """
                                <table width="100%" cellpadding="0" cellspacing="0" style="font-family: 'Inter', Arial, sans-serif; background:#fef2f2; padding:32px;">
                                    <tr><td align="center">
                                        <table width="640" cellpadding="0" cellspacing="0" style="background:#ffffff; border-radius:16px; border:1px solid #fecdd3;">
                                            <tr>
                                                <td style="padding:32px; color:#7f1d1d;">
                                                    <h2 style="margin:0 0 12px;">We noticed a {{ action }}</h2>
                                                    <p style="margin:0 0 16px;">Time: {{ timestamp }} · IP: {{ ip_address }}</p>
                                                    <p style="margin:0 0 20px;">If this wasn’t you, secure your account immediately.</p>
                                                    <a href="{{ secure_account_url }}" style="background:#b91c1c; color:#fff1f2; padding:12px 24px; border-radius:8px; text-decoration:none; font-weight:600;">Secure account</a>
                                                    <p style="margin:24px 0 0; font-size:14px;">Security desk: {{ support_email }}</p>
                                                </td>
                                            </tr>
                                        </table>
                                    </td></tr>
                                </table>
                        """.strip(),
                        'plain_text_content': (
                                "Security alert: {{ action }}\n"
                                "Time: {{ timestamp }}\n"
                                "IP: {{ ip_address }}\n\n"
                                "Secure your account: {{ secure_account_url }}\n"
                                "Help: {{ support_email }}"
                        ),
                        'variables': ['user_name', 'action', 'timestamp', 'ip_address', 'secure_account_url', 'support_email'],
                        'is_active': True,
                        'is_default': True,
                },
        ]

        for template in templates:
                defaults = template.copy()
                defaults.pop('template_type')
                defaults.pop('language')
                EmailTemplate.objects.update_or_create(
                        template_type=template['template_type'],
                        language=template['language'],
                        defaults=defaults,
                )


def remove_email_templates(apps, schema_editor):
        EmailTemplate = apps.get_model('notifications', 'EmailTemplate')
        template_types = [
                'booking_confirmation',
                'booking_cancellation',
                'payment_receipt',
                'welcome',
                'review_reminder',
                'security_alert',
        ]
        EmailTemplate.objects.filter(template_type__in=template_types, language='en').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_initial'),
    ]

    operations = [
        migrations.RunPython(seed_email_templates, remove_email_templates),
    ]
