# Generated by Django 5.2.11 on 2026-03-02 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_add_booking_reminder_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='template_type',
            field=models.CharField(choices=[('booking_confirmation', 'Booking Confirmation'), ('booking_reminder', 'Booking Reminder'), ('booking_cancellation', 'Booking Cancellation'), ('payment_receipt', 'Payment Receipt'), ('password_reset', 'Password Reset'), ('welcome', 'Welcome Email'), ('promotional', 'Promotional'), ('review_reminder', 'Review Reminder'), ('security_alert', 'Security Alert')], max_length=50, verbose_name='template type'),
        ),
    ]
