# Generated by Django 5.2.11 on 2026-02-26 15:14

import django.core.validators
import django.db.models.deletion
import django_countries.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_rentals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarDriver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='full name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='phone')),
                ('license_number', models.CharField(max_length=100, unique=True, verbose_name='license number')),
                ('license_country', django_countries.fields.CountryField(max_length=2, verbose_name='license country')),
                ('years_experience', models.PositiveSmallIntegerField(default=1, verbose_name='years of experience')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('average_rating', models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='average rating')),
                ('review_count', models.PositiveIntegerField(default=0, verbose_name='review count')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drivers', to='car_rentals.carrentalcompany')),
            ],
            options={
                'verbose_name': 'car driver',
                'verbose_name_plural': 'car drivers',
                'ordering': ['full_name'],
            },
        ),
        migrations.AddField(
            model_name='carrentalbooking',
            name='selected_driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='car_rentals.cardriver'),
        ),
        migrations.CreateModel(
            name='CarDriverReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='rating')),
                ('feedback', models.TextField(verbose_name='feedback')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='driver_review', to='car_rentals.carrentalbooking')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='car_rentals.cardriver')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'car driver review',
                'verbose_name_plural': 'car driver reviews',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('driver', 'user'), name='unique_driver_review_per_user')],
            },
        ),
    ]
