# Generated by Django 5.2.11 on 2026-02-26 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_rentals', '0002_cardriver_carrentalbooking_selected_driver_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardriver',
            name='cars',
            field=models.ManyToManyField(blank=True, related_name='assigned_drivers', to='car_rentals.car', verbose_name='assigned cars'),
        ),
    ]
