# Generated by Django 5.2.11 on 2026-02-27 23:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_rentals', '0003_cardriver_cars'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='current_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='current latitude'),
        ),
        migrations.AddField(
            model_name='car',
            name='current_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='current longitude'),
        ),
        migrations.AddField(
            model_name='car',
            name='engine_capacity',
            field=models.CharField(blank=True, help_text='e.g. 2.0L', max_length=20, verbose_name='engine capacity'),
        ),
        migrations.AddField(
            model_name='car',
            name='featured_image',
            field=models.ImageField(blank=True, help_text='Main display image for this car', upload_to='cars/featured/', verbose_name='featured image'),
        ),
        migrations.AddField(
            model_name='car',
            name='fuel_consumption',
            field=models.CharField(blank=True, help_text='e.g. 8L/100km', max_length=30, verbose_name='fuel consumption'),
        ),
        migrations.AddField(
            model_name='car',
            name='has_child_seat',
            field=models.BooleanField(default=False, verbose_name='child seat available'),
        ),
        migrations.AddField(
            model_name='car',
            name='has_dashcam',
            field=models.BooleanField(default=False, verbose_name='dashcam'),
        ),
        migrations.AddField(
            model_name='car',
            name='has_wifi',
            field=models.BooleanField(default=False, verbose_name='WiFi hotspot'),
        ),
        migrations.AddField(
            model_name='car',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='featured car'),
        ),
        migrations.AddField(
            model_name='car',
            name='location_updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='location last updated'),
        ),
        migrations.AddField(
            model_name='car',
            name='service_type',
            field=models.CharField(choices=[('rental', 'Self-Drive Rental'), ('taxi', 'Taxi / Chauffeur'), ('both', 'Rental & Taxi')], default='rental', help_text='Whether this car is available for rental, taxi, or both', max_length=10, verbose_name='service type'),
        ),
        migrations.AddField(
            model_name='car',
            name='taxi_base_fare',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Base fare for taxi service', max_digits=8, null=True, verbose_name='taxi base fare'),
        ),
        migrations.AddField(
            model_name='car',
            name='taxi_per_hour',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Rate per hour for taxi service', max_digits=8, null=True, verbose_name='taxi hourly rate'),
        ),
        migrations.AddField(
            model_name='car',
            name='taxi_rate_per_km',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Rate per kilometer for taxi service', max_digits=8, null=True, verbose_name='taxi rate per km'),
        ),
        migrations.AddField(
            model_name='carcategory',
            name='icon',
            field=models.CharField(blank=True, help_text='Font Awesome icon class, e.g. fa-car', max_length=50, verbose_name='icon class'),
        ),
        migrations.AddField(
            model_name='cardriver',
            name='current_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='current latitude'),
        ),
        migrations.AddField(
            model_name='cardriver',
            name='current_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='current longitude'),
        ),
        migrations.AddField(
            model_name='cardriver',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='currently available'),
        ),
        migrations.AddField(
            model_name='cardriver',
            name='languages_spoken',
            field=models.CharField(blank=True, help_text='Comma-separated', max_length=200, verbose_name='languages spoken'),
        ),
        migrations.AddField(
            model_name='cardriver',
            name='location_updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='location last updated'),
        ),
        migrations.AddField(
            model_name='cardriver',
            name='photo',
            field=models.ImageField(blank=True, upload_to='drivers/photos/', verbose_name='photo'),
        ),
        migrations.AddField(
            model_name='carrentalcompany',
            name='logo',
            field=models.ImageField(blank=True, upload_to='car_companies/logos/', verbose_name='logo'),
        ),
        migrations.AddField(
            model_name='carrentalcompany',
            name='offers_rental',
            field=models.BooleanField(default=True, verbose_name='offers car rental'),
        ),
        migrations.AddField(
            model_name='carrentalcompany',
            name='offers_taxi',
            field=models.BooleanField(default=False, verbose_name='offers taxi service'),
        ),
        migrations.AddField(
            model_name='rentallocation',
            name='supports_taxi_pickup',
            field=models.BooleanField(default=True, verbose_name='supports taxi pickup'),
        ),
        migrations.AlterField(
            model_name='car',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('rented', 'Rented'), ('on_trip', 'On Trip'), ('maintenance', 'Maintenance'), ('reserved', 'Reserved')], default='available', max_length=20, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='cardriverreview',
            name='booking',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='driver_review', to='car_rentals.carrentalbooking'),
        ),
        migrations.AlterField(
            model_name='rentallocation',
            name='location_type',
            field=models.CharField(choices=[('airport', 'Airport'), ('downtown', 'Downtown'), ('station', 'Train/Bus Station'), ('hotel', 'Hotel'), ('custom', 'Custom Address'), ('other', 'Other')], max_length=20, verbose_name='location type'),
        ),
        migrations.CreateModel(
            name='CarImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='cars/gallery/', verbose_name='image')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='caption')),
                ('is_primary', models.BooleanField(default=False, verbose_name='primary image')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='display order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='car_rentals.car')),
            ],
            options={
                'verbose_name': 'car image',
                'verbose_name_plural': 'car images',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='TaxiBooking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('booking_reference', models.CharField(editable=False, max_length=20, unique=True, verbose_name='booking reference')),
                ('trip_type', models.CharField(choices=[('one_way', 'One Way'), ('round_trip', 'Round Trip'), ('hourly', 'Hourly Hire'), ('airport_transfer', 'Airport Transfer'), ('city_tour', 'City Tour')], default='one_way', max_length=20, verbose_name='trip type')),
                ('pickup_address', models.TextField(verbose_name='pickup address')),
                ('pickup_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='pickup latitude')),
                ('pickup_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='pickup longitude')),
                ('pickup_datetime', models.DateTimeField(verbose_name='pickup date & time')),
                ('dropoff_address', models.TextField(verbose_name='dropoff address')),
                ('dropoff_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='dropoff latitude')),
                ('dropoff_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='dropoff longitude')),
                ('hours_booked', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='hours booked')),
                ('passenger_name', models.CharField(max_length=255, verbose_name='passenger name')),
                ('passenger_phone', models.CharField(max_length=50, verbose_name='passenger phone')),
                ('passenger_email', models.EmailField(blank=True, max_length=254, verbose_name='passenger email')),
                ('number_of_passengers', models.PositiveSmallIntegerField(default=1, verbose_name='number of passengers')),
                ('luggage_count', models.PositiveSmallIntegerField(default=0, verbose_name='luggage pieces')),
                ('flight_number', models.CharField(blank=True, max_length=20, verbose_name='flight number')),
                ('flight_arrival_time', models.DateTimeField(blank=True, null=True, verbose_name='flight arrival time')),
                ('estimated_distance_km', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='estimated distance (km)')),
                ('estimated_duration_minutes', models.PositiveIntegerField(blank=True, null=True, verbose_name='estimated duration (minutes)')),
                ('base_fare', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='base fare')),
                ('distance_charge', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='distance charge')),
                ('time_charge', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='time charge')),
                ('surge_multiplier', models.DecimalField(decimal_places=2, default=1.0, max_digits=4, verbose_name='surge multiplier')),
                ('taxes', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='taxes')),
                ('total_fare', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='total fare')),
                ('currency', models.CharField(default='USD', max_length=3, verbose_name='currency')),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20, verbose_name='payment status')),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('mobile', 'Mobile Money')], default='card', max_length=20, verbose_name='payment method')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('driver_assigned', 'Driver Assigned'), ('en_route', 'Driver En Route'), ('arrived', 'Driver Arrived'), ('in_progress', 'Trip In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], default='pending', max_length=20, verbose_name='status')),
                ('actual_pickup_time', models.DateTimeField(blank=True, null=True, verbose_name='actual pickup time')),
                ('actual_dropoff_time', models.DateTimeField(blank=True, null=True, verbose_name='actual dropoff time')),
                ('actual_distance_km', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='actual distance (km)')),
                ('special_requests', models.TextField(blank=True, verbose_name='special requests')),
                ('is_business_booking', models.BooleanField(default=False, verbose_name='business booking')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('car', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taxi_bookings', to='car_rentals.car')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='taxi_bookings', to='car_rentals.carcategory')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='taxi_bookings', to='car_rentals.carrentalcompany')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taxi_trips', to='car_rentals.cardriver')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='taxi_bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'taxi booking',
                'verbose_name_plural': 'taxi bookings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='cardriverreview',
            name='taxi_booking',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='driver_review', to='car_rentals.taxibooking'),
        ),
        migrations.CreateModel(
            name='CarLocationTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='latitude')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='longitude')),
                ('speed_kmh', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='speed (km/h)')),
                ('heading', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='heading (degrees)')),
                ('recorded_at', models.DateTimeField(auto_now_add=True, verbose_name='recorded at')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_history', to='car_rentals.car')),
            ],
            options={
                'verbose_name': 'car location log',
                'verbose_name_plural': 'car location logs',
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['car', '-recorded_at'], name='car_rentals_car_id_019f20_idx')],
            },
        ),
    ]
