# Generated by Django 5.2.11 on 2026-02-28 10:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_rentals', '0004_car_current_latitude_car_current_longitude_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarAvailability',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='active')),
                ('date', models.DateField(db_index=True, verbose_name='date')),
                ('is_available', models.BooleanField(default=True, verbose_name='available')),
                ('price_override', models.DecimalField(blank=True, decimal_places=2, help_text='Optional override price for this date', max_digits=10, null=True, verbose_name='price override')),
            ],
            options={
                'verbose_name': 'car availability',
                'verbose_name_plural': 'car availability',
            },
        ),
        migrations.AddField(
            model_name='car',
            name='daily_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Base rental price per day', max_digits=10, verbose_name='daily price'),
        ),
        migrations.AddField(
            model_name='car',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='deleted at'),
        ),
        migrations.AddField(
            model_name='car',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_soft_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='car',
            name='dropoff_location',
            field=models.CharField(blank=True, max_length=255, verbose_name='dropoff location'),
        ),
        migrations.AddField(
            model_name='car',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='active'),
        ),
        migrations.AddField(
            model_name='car',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, verbose_name='deleted'),
        ),
        migrations.AddField(
            model_name='car',
            name='moderation_status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('inactive', 'Inactive')], default='pending', help_text='Approval state for public listing', max_length=20, verbose_name='listing status'),
        ),
        migrations.AddField(
            model_name='car',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='Listing owner/car provider', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='owned_cars', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='car',
            name='pickup_location',
            field=models.CharField(blank=True, max_length=255, verbose_name='pickup location'),
        ),
        migrations.AddField(
            model_name='car',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=255, unique=True, verbose_name='slug'),
        ),
        migrations.AddField(
            model_name='carimage',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='active'),
        ),
        migrations.AddField(
            model_name='carimage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='car',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('rented', 'Rented'), ('on_trip', 'On Trip'), ('maintenance', 'Maintenance'), ('reserved', 'Reserved')], default='available', max_length=20, verbose_name='operational status'),
        ),
        migrations.AlterField(
            model_name='car',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='carimage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='carimage',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='carrentalbooking',
            name='car',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rental_bookings', to='car_rentals.car'),
        ),
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['moderation_status', 'status'], name='car_rentals_moderat_9dae21_idx'),
        ),
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['daily_price'], name='car_rentals_daily_p_bbf928_idx'),
        ),
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['pickup_location', 'dropoff_location'], name='car_rentals_pickup__60347a_idx'),
        ),
        migrations.AddField(
            model_name='caravailability',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='car_rentals.car'),
        ),
        migrations.AddIndex(
            model_name='caravailability',
            index=models.Index(fields=['car', 'date'], name='car_rentals_car_id_1d3024_idx'),
        ),
        migrations.AddIndex(
            model_name='caravailability',
            index=models.Index(fields=['car', 'date', 'is_available'], name='car_rentals_car_id_2db654_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='caravailability',
            unique_together={('car', 'date')},
        ),
    ]
