# Generated by Django 5.2.11 on 2026-02-28 21:19

import django_countries.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_role'),
        ('car_rentals', '0005_caravailability_car_daily_price_car_deleted_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carcategory',
            options={'ordering': ['display_order', 'name'], 'verbose_name': 'car category', 'verbose_name_plural': 'car categories'},
        ),
        migrations.RemoveIndex(
            model_name='car',
            name='car_rentals_daily_p_bbf928_idx',
        ),
        migrations.RemoveIndex(
            model_name='car',
            name='car_rentals_pickup__60347a_idx',
        ),
        migrations.AlterUniqueTogether(
            name='rentalrate',
            unique_together={('company', 'location', 'category', 'valid_from', 'valid_to')},
        ),
        migrations.RemoveField(
            model_name='car',
            name='dropoff_location',
        ),
        migrations.RemoveField(
            model_name='car',
            name='pickup_location',
        ),
        migrations.AlterField(
            model_name='car',
            name='featured_image',
            field=models.ImageField(blank=True, help_text='Main display image for this car', null=True, upload_to='cars/featured/', verbose_name='featured image'),
        ),
        migrations.AlterField(
            model_name='car',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='cardriver',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='drivers/photos/', verbose_name='photo'),
        ),
        migrations.AlterField(
            model_name='carrentalbooking',
            name='daily_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='daily rate'),
        ),
        migrations.AlterField(
            model_name='carrentalbooking',
            name='driver_age',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='driver age'),
        ),
        migrations.AlterField(
            model_name='carrentalbooking',
            name='driver_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='driver email'),
        ),
        migrations.AlterField(
            model_name='carrentalbooking',
            name='driver_license_country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, verbose_name='license country'),
        ),
        migrations.AlterField(
            model_name='carrentalbooking',
            name='driver_license_expiry',
            field=models.DateField(blank=True, null=True, verbose_name='license expiry'),
        ),
        migrations.AlterField(
            model_name='carrentalbooking',
            name='driver_license_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='license number'),
        ),
        migrations.AlterField(
            model_name='carrentalbooking',
            name='driver_phone',
            field=models.CharField(blank=True, max_length=50, verbose_name='driver phone'),
        ),
        migrations.AlterField(
            model_name='carrentalbooking',
            name='insurance_type',
            field=models.CharField(blank=True, choices=[('basic', 'Basic'), ('full', 'Full Coverage'), ('premium', 'Premium'), ('none', 'None')], default='basic', max_length=50, verbose_name='insurance type'),
        ),
        migrations.AlterField(
            model_name='carrentalbooking',
            name='rental_days',
            field=models.PositiveIntegerField(default=1, verbose_name='rental days'),
        ),
        migrations.AlterField(
            model_name='carrentalbooking',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='subtotal'),
        ),
        migrations.AlterField(
            model_name='carrentalbooking',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='total amount'),
        ),
        migrations.AlterField(
            model_name='carrentalcompany',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, verbose_name='country'),
        ),
        migrations.AlterField(
            model_name='carrentalcompany',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='car_companies/logos/', verbose_name='logo'),
        ),
        migrations.AlterField(
            model_name='rentallocation',
            name='opening_hours',
            field=models.JSONField(blank=True, default=dict, help_text='Opening hours in JSON format', verbose_name='opening hours'),
        ),
        migrations.AlterField(
            model_name='rentallocation',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, verbose_name='postal code'),
        ),
        migrations.AlterField(
            model_name='rentalrate',
            name='insurance_options',
            field=models.JSONField(blank=True, default=dict, help_text='Insurance options and prices in JSON', verbose_name='insurance options'),
        ),
        migrations.AlterUniqueTogether(
            name='rentallocation',
            unique_together={('company', 'name', 'city')},
        ),
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['company', 'status'], name='car_rentals_company_7c1a03_idx'),
        ),
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['category', 'status'], name='car_rentals_categor_3b562a_idx'),
        ),
        migrations.AddIndex(
            model_name='carrentalbooking',
            index=models.Index(fields=['booking_reference'], name='car_rentals_booking_bd6c40_idx'),
        ),
        migrations.AddIndex(
            model_name='carrentalbooking',
            index=models.Index(fields=['user', '-created_at'], name='car_rentals_user_id_d08b86_idx'),
        ),
        migrations.AddIndex(
            model_name='carrentalbooking',
            index=models.Index(fields=['status'], name='car_rentals_status_437439_idx'),
        ),
        migrations.AddIndex(
            model_name='taxibooking',
            index=models.Index(fields=['booking_reference'], name='car_rentals_booking_394ab9_idx'),
        ),
        migrations.AddIndex(
            model_name='taxibooking',
            index=models.Index(fields=['user', '-created_at'], name='car_rentals_user_id_a256fc_idx'),
        ),
        migrations.AddIndex(
            model_name='taxibooking',
            index=models.Index(fields=['status'], name='car_rentals_status_f51ef7_idx'),
        ),
    ]
