# Generated by Django 5.2.11 on 2026-03-02 00:35

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_rentals', '0006_alter_carcategory_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='average_rating',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Rolling average from renter reviews', max_digits=3, verbose_name='average rating'),
        ),
        migrations.AddField(
            model_name='car',
            name='review_count',
            field=models.PositiveIntegerField(default=0, verbose_name='review count'),
        ),
        migrations.AddField(
            model_name='car',
            name='usage_function',
            field=models.CharField(choices=[('mini', 'City / Mini'), ('taxi', 'Taxi & Ride-hailing'), ('safari', 'Safari & Overland'), ('executive', 'Executive Transfer'), ('logistics', 'Utility & Logistics')], default='mini', help_text='Headline use case travelers should expect (mini, taxi, safari, executive, logistics).', max_length=20, verbose_name='primary function'),
        ),
        migrations.CreateModel(
            name='CarRentalReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='rating')),
                ('feedback', models.TextField(blank=True, verbose_name='feedback')),
                ('available_after', models.DateTimeField(default=django.utils.timezone.now, help_text='User can submit once this timestamp is reached', verbose_name='review window opens')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='car_review', to='car_rentals.carrentalbooking')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='car_rentals.car')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'car rental review',
                'verbose_name_plural': 'car rental reviews',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('car', 'user'), name='unique_car_review_per_user')],
            },
        ),
    ]
