# Generated by Django 5.2.11 on 2026-03-01 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='city',
            new_name='locations_c_country_a5360f_idx',
            old_name='locations_ci_country_5dc14c_idx',
        ),
        migrations.RenameIndex(
            model_name='city',
            new_name='locations_c_populat_a89b82_idx',
            old_name='locations_ci_populat_3f96c5_idx',
        ),
        migrations.RenameIndex(
            model_name='city',
            new_name='locations_c_timezon_25ac15_idx',
            old_name='locations_ci_timezon_953f1c_idx',
        ),
        migrations.RenameIndex(
            model_name='city',
            new_name='locations_c_feature_253fc3_idx',
            old_name='locations_ci_feature_00fbd5_idx',
        ),
        migrations.RenameIndex(
            model_name='country',
            new_name='locations_c_iso2_252519_idx',
            old_name='locations_co_iso2_c044e0_idx',
        ),
        migrations.RenameIndex(
            model_name='country',
            new_name='locations_c_iso3_e98cc3_idx',
            old_name='locations_co_iso3_0ea5e7_idx',
        ),
    ]
